### ISSUE TITLE
tests fail after latest merge

### ISSUE THREAD

**Issue by priv-kweihmann** [vinland-technology/flict#142] opened 2021-11-10 12:07 UTC
# Description

First of all, thank you for your bug report. Please fill out below sections (if applicable) to help us fix the issue as good and fast as possible.

## Steps for reproduction

> Please add a description how to reproduce the seen behavior

Run test pipeline

## Expected behavior

> What is the expected behavior?

all green

## Actual behavior

> What do you see instead?

some failed tests, likely due to changed DB from latest merge

## Environment

 | tool    | version    | how to get it       |
 | ------- | ---------- | ------------------- |
 | flict   | !!enter here!! | `flict --version`   |
 | python3 | !!enter here!! | `python3 --version` |
 | os      | !!enter here!! | n.a.                |

> add additional tools you used and their versions here

## Additional logs

> If you can provide any logs or additional info, please add them here

> display-compatibility MIT:              ERROR:flict:Could not parse license expression: None

https://github.com/vinland-technology/flict/runs/4164806177?check_suite_focus=true

**Comment by hesa** [comment] 2021-11-13 10:23
Weird. Can't reproduce it locally. I am on it

**Comment by hesa** [comment] 2021-11-13 11:16
Getting intermittent errors :(
Only from the bash scripts... perhaps it's about time

**Comment by jens-erdmann** [comment] 2021-11-20 09:03
Fixed with #151

**Closed as completed by jens-erdmann** 2021-11-20 09:03 UTC
Labels: bug
